spring.application.name=caronte
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=${PORT:8080}

# Spring Configuration
spring.main.lazy-initialization=true
spring.devtools.restart.enabled=false
server.tomcat.max-threads=50
server.tomcat.min-spare-threads=10

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never

# JWT Properties
caronte.app.jwt.secret=${JWT_SECRET}
caronte.app.jwt.expiration=${JWT_EXPIRATION:86400000}

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Deactivate Swagger
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
