spring.application.name=caronte
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=${PORT:8080}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# JWT Propereties
caronte.app.jwt.secret=${JWT_SECRET}
caronte.app.jwt.expiration=${JWT_EXPIRATION:86400000} 

# Stripe
stripe.customer.premium.price.id=${PLAN_PREMIUM_CUSTOMER_ID}
stripe.company.premium.price.id=${PLAN_PREMIUM_COMPANY_ID}
stripe.api.key=${STRIPE_PRIVATE_KEY}
stripe.obituary.price.id=price_1R3GluGa0d4217RGL5hpbiZr

#Enviar esquelas por email
# Email Properties
# Email Properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=isaacsolpad@gmail.com
spring.mail.password=vcnp pccs iplm bgfr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.domain=https://sprint3.caronte.site/

# Cloudinary
cloudinary.video.url=${CLOUDINARY_IMAGES_URL}
cloudinary.image.url=${CLOUDINARY_IMAGES_URL}

# AES Encryption
security.aes.secret-key=L9xV7eRp2MfYqT1zWs3NjKg4UbXaCr0Q
