name: Codacy Analysis

on:
  pull_request:
    branches: [develop]
    types: [opened, reopened, edited, review_requested, synchronize]
  push:
    branches:
      - "develop"
  workflow_call:

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Install Codacy CLI
        run: |
          wget https://download.codacy.com/cli/linux/codacy-cli-5.0.0-linux-amd64.tar.gz
          tar -xzf codacy-cli-5.0.0-linux-amd64.tar.gz
          sudo mv codacy-cli-*/codacy-cli /usr/local/bin/codacy-cli

      - name: Run Codacy Analysis
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_TOKEN }}
        run: |
          codacy-cli -r .
